# Generated by Django 3.2.8 on 2021-10-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCliente', models.IntegerField()),
                ('nombreCliente', models.CharField(max_length=50)),
                ('movilCliente', models.CharField(max_length=9)),
                ('edadCliente', models.IntegerField()),
                ('correoCliente', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codServicio', models.IntegerField()),
                ('nombreServicio', models.CharField(max_length=50)),
                ('precioServicio', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='boletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codBoleta', models.IntegerField()),
                ('fechaBoleta', models.DateField()),
                ('codCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
                ('codServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicios')),
            ],
        ),
    ]
